node {
  stage('clone'){
      sh "clone git"
      git 'https://github.com/minchocosong/vue-test.git'
  }

  def image = props['image']
  def tag = props['version']
  def dockerRegistry = props['dockerRegistry']
   
  stage('docker build'){
    sh "echo 'Build Jar'"
    container('docker') {
      docker.withRegistry("${dockerRegistry}", 'registry-credentials') {
        sh "docker build -t ${image}:${tag} ."
        sh "docker push ${image}:${tag}"
        sh "docker tag ${image}:${tag} ${image}:latest"
        sh "docker push ${image}:latest"
      }
    }
  }
   
  stage('kubernetes deploy'){
      sh "echo 'Deploy k8s'"
      container('kubectl') {
        withCredentials([[$class: 'UsernamePasswordMultiBinding',
                  credentialsId: 'registry-credentials',
                  usernameVariable: 'minchoco',
                  passwordVariable: 'alswjd17']]) {
          
          sh "kubectl delete deployments -n ${namespace} --selector=app=${selector}"
          sh "sleep 5"
          sh "kubectl apply -n ${namespace} -f ${deployment}"
          sh "sleep 5"
          sh "kubectl apply -n ${namespace} -f ${service}"
        }
      }
  }
}