apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-test
  labels:
    app: vue-test
spec:
  selector:
    matchLabels:
      app: vue-test
  replicas: 1
  template:
    metadata:
      labels:
        app: vue-test
    spec:
      containers:
      - name: vue-test
        image: minchoco/vue-test
        imagePullPolicy: Always
        ports:
        - containerPort: 8080